spring:
  application:
    name: e-com-spring

  liquibase:
    change-log: classpath:/db/master.xml
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/e_com_spring
    username: postgres
    password: npmstart
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    liquibase: INFO